---
- name: Set up Docker
  hosts: all
  become: true

  vars_files:
    - vars.yml

  tasks:
    - name: Install python3-docker package via apt
      ansible.builtin.apt:
        name: python3-docker
        state: present

  roles:
    - geerlingguy.docker
