---
java_packages:
  - openjdk-17-jdk

# jenkins2_config_http_port: 8080
# jenkins_admin_username: "{{ jenkins_admin_username_secret }}"
# jenkins_admin_password: "{{ jenkins_admin_password_secret }}"
# jenkins_hostname: klegg
jenkins_apt_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io-2026.key
jenkins_stable_url: https://pkg.jenkins.io/debian-stable
